name: Test tressed

on: [push]

jobs:
  test:
    name: python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.14", "3.14t"]

    steps:
      - uses: actions/checkout@v6.0.0

        # See https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7.1.4
        with:
          # Install a specific version of uv.
          version: "0.9.13"
          python-version: ${{ matrix.python-version }}

      - name: "Set up Python"
        uses: actions/setup-python@v6.1.0
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run test target
        run: make test

